USER = "USER"
MOVIES = "MOVIES"
SECUENCE = "SECUENCE"
RESERVATION = "RESERVATION"
ROOM = "ROOM"
ROOM_CONFIGURATION = "ROOM_CONFIGURATION"
USER_PAYMENT = "USER_PAYMENT"
TICKET_VALUE ="TICKET_VALUE"
PAYMENT_METHODS="PAYMENT_METHODS"
#general properties
ID = "id"
DELETED = "deleted"
TYPE = "type"


#Room properties

ROOM_NAME = "name"
ROOM_ROWS = "rows"
ROOM_COLUMNS = "columns"
ROOM_FIELDS = [ID,ROOM_NAME,ROOM_ROWS,ROOM_COLUMNS]
#Room configuration proeprties

CONFIG_ROOM_ID = "roomId"
CONFIG_DAY = "day"
CONFIG_TIME = "time"
CONFIG_MOVIE_ID = "movieId"
CONFIG_FIELDS = [ID,CONFIG_MOVIE_ID,CONFIG_ROOM_ID,CONFIG_DAY,CONFIG_TIME,]

# reservation properties

RESERVATION_ROOM_ID = "roomId"
RESERVATION_USER_ID = "userId"
RESERVATION_DAY = "day"
RESERVATION_TIME = "time"
RESERVATION_ROW = "row"
RESERVATION_COLUMN = "column"
RESERVATION_FIELDS = [ID,RESERVATION_ROOM_ID,RESERVATION_USER_ID,RESERVATION_DAY,RESERVATION_TIME,RESERVATION_ROW,RESERVATION_COLUMN]


MOVIE_TITLE="title"
MOVIE_DURATION="duration"
MOVIE_GENRE="genre"
MOVIE_CATEGORY="category"
MOVIE_RATING="rating"
MOVIE_RELEASEDATE="releaseDate"

MOVIES_FIELDS=[ID,MOVIE_TITLE,MOVIE_DURATION,MOVIE_GENRE,MOVIE_CATEGORY,MOVIE_RATING,MOVIE_RELEASEDATE]


USER_USERNAME="userName"
USER_NAME= "name"
USER_LASTNAME="lastName"
USER_PASSWORD="password"
USER_ROLE="role"
USER_EMAIL="email"

USERS_FIELDS= [ID,USER_USERNAME,USER_NAME,USER_LASTNAME,USER_PASSWORD,USER_ROLE,USER_EMAIL]
USERS_FIELDS_EDIT = [ID,USER_USERNAME,USER_NAME,USER_LASTNAME,USER_PASSWORD,USER_EMAIL]

#Invoice

INVOICE = "INVOICE"
INVOICE_USER = "userId"
INVOICE_AMOUNT ="amount"
INVOICE_DATE = "invoiceDate"
INVOICE_RESERVATION = "INVOICE_RESERVATION"
INVOICE_RESERVATION_INVOICE_ID = "invoiceID"
INVOICE_RESERVATION_RESERVATION_ID = "reservationId"


INVOICE_FIELDS = [ID,INVOICE_USER,INVOICE_AMOUNT,INVOICE_DATE]
INVOICE_RESERVATION_FIELDS = [INVOICE_RESERVATION_INVOICE_ID,INVOICE_RESERVATION_RESERVATION_ID]

USER_PAYMENT_USER_ID="user_idBalance"
USER_PAYMENT_CASH="CashBalance"
USER_PAYMENT_TRANSFER="TransferBalance"
USER_PAYMENT_DEBIT="DebitBalance"
USER_PAYMENT_CREDIT="CreditBalance"
USER_PAYMENT_POINTS="PointsBalance"
USER_PAYMENT_FIELDS = [ID,USER_PAYMENT_USER_ID,USER_PAYMENT_CASH,USER_PAYMENT_TRANSFER,USER_PAYMENT_DEBIT,USER_PAYMENT_CREDIT,USER_PAYMENT_POINTS]
USER_PAYMENT_FIELDS_EDIT = [ID,USER_PAYMENT_CASH,USER_PAYMENT_TRANSFER,USER_PAYMENT_DEBIT,USER_PAYMENT_CREDIT,USER_PAYMENT_POINTS]

TICKET_VALUE_VALUE = "ticketValue"
TICKET_VALUE_FIELDS = [ID,TICKET_VALUE_VALUE]

PAYMENT_METHODS_CASH="Cash"
PAYMENT_METHODS_TRANSFER="Transfer"
PAYMENT_METHODS_DEBIT="Debit"
PAYMENT_METHODS_CREDIT="Credit"
PAYMENT_METHODS_POINTS="Points"

PAYMENT_METHODS_FIELDS = [ID,PAYMENT_METHODS_CASH,PAYMENT_METHODS_TRANSFER,PAYMENT_METHODS_DEBIT,PAYMENT_METHODS_CREDIT,PAYMENT_METHODS_POINTS]

# Opciones de método de pago
"""
PAYMENT_METHODS = {
    1: "Cash",
    2: "Transfer",
    3: "Debit",
    4: "Credit",
    5: "Points"
}"""

FIELDS = {
    USER: USERS_FIELDS,
    MOVIES: MOVIES_FIELDS,
    SECUENCE: "SECUENCE",
    RESERVATION: RESERVATION_FIELDS,
    ROOM: ROOM_FIELDS,
    ROOM_CONFIGURATION: CONFIG_FIELDS,
    INVOICE: INVOICE_FIELDS,
    INVOICE_RESERVATION:INVOICE_RESERVATION_FIELDS,
    USER_PAYMENT: USER_PAYMENT_FIELDS,
    TICKET_VALUE: TICKET_VALUE_FIELDS,
    PAYMENT_METHODS:PAYMENT_METHODS_FIELDS
}

STRING = "string"
INTEGER = "integer"
FLOAT = "float"
DATE = "date"



def convertValue(value,type):
    match type:
        case "string":
            return value
        case "float":
            return float(value)
        case "integer":
            return int(value)
        case "date":
            return value
        

#Se agrega el field  y el tipo de campo que es
FIELDS_TYPES = {

    USER_USERNAME:STRING,
    USER_NAME:STRING,
    USER_LASTNAME:STRING,
    USER_PASSWORD:STRING,
    USER_ROLE:INTEGER,
    USER_EMAIL:STRING,

    MOVIE_TITLE:STRING ,
    MOVIE_DURATION:INTEGER,
    MOVIE_GENRE:STRING,
    MOVIE_CATEGORY:STRING,
    MOVIE_RATING:INTEGER,
    MOVIE_RELEASEDATE:DATE,

    RESERVATION_ROOM_ID:STRING,
    RESERVATION_USER_ID:INTEGER,
    RESERVATION_DAY:STRING, 
    RESERVATION_TIME:STRING, 
    RESERVATION_ROW:INTEGER, 
    RESERVATION_COLUMN:INTEGER,

    INVOICE_AMOUNT:FLOAT,
    INVOICE_USER:INTEGER,
    INVOICE_DATE:STRING,
    INVOICE_RESERVATION_INVOICE_ID:INTEGER,
    INVOICE_RESERVATION_RESERVATION_ID:INTEGER,

    ROOM_COLUMNS:INTEGER,
    ROOM_NAME:STRING,
    ROOM_ROWS:INTEGER,

    CONFIG_ROOM_ID:INTEGER,
    CONFIG_MOVIE_ID:INTEGER,
    CONFIG_DAY:DATE,
    CONFIG_TIME:STRING,

    USER_PAYMENT_USER_ID:INTEGER,
    USER_PAYMENT_CASH:FLOAT,
    USER_PAYMENT_TRANSFER:FLOAT,
    USER_PAYMENT_DEBIT:FLOAT,
    USER_PAYMENT_CREDIT:FLOAT,
    USER_PAYMENT_POINTS:FLOAT,

    PAYMENT_METHODS_CASH:FLOAT,
    PAYMENT_METHODS_TRANSFER:FLOAT,
    PAYMENT_METHODS_DEBIT:FLOAT,
    PAYMENT_METHODS_CREDIT:FLOAT,
    PAYMENT_METHODS_POINTS:FLOAT,

    TICKET_VALUE_VALUE:FLOAT
}







   
